version: "3.8"

services:
  api:
    image: gtd/leaderboards
    build:
      context: ..
      dockerfile: docker/Dockerfile
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: postgres://postgres:gtd-leaderboards-db@localhost:5433/postgres

  db:
    image: postgres:15.1-bullseye
    restart: always
    environment:
      POSTGRES_PASSWORD: gtd-leaderboards-db
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    name: gtd-leaderboards-db-pgdata
